imap_data_access/io.py, tests/test_io.py
Passing a pathlib object before caused errors on the `"/" in file_path` check due to it not being a string. We should only go down that path if we are passed strings, so add that case and add an explicit test for passing Path objects.
=> FIX: Allow Path or string to download routine

imap_data_access/io.py, tests/test_io.py
This allows relative paths and strings to be uploaded. Before the routines required the absolute path even if you were in the data directory.
=> FIX: Allow relative paths and strings to be input to upload

README.md, imap_data_access/cli.py
This avoids the stack traces and only prints the messages of what hapened with the server errors instead.
Are these print statements what you'd expect to see as a user?
```bash
$ imap-data-access download a/b/c.txt
HTTP Error: 502 - Bad Gateway
Server Message: {"message": "Internal server error"}
```
=> FIX: Catch errors when using the CLI

README.md
This PR makes minor updates to the README:
- Updated upload example to avoid use of calibration files, which are currently not supported
- Added sentence about what happens if user does not set the `IMAP_DATA_DIR` env variable
=> Updates to README examples, IMAP_DATA_DIR clarification

README.md, imap_data_access/__init__.py, imap_data_access/file_naming.py, imap_data_access/file_validation.py, imap_data_access/io.py, tests/test_file_validation.py, tests/test_io.py
Moving some of the file management stuff from sds-data-manager to this repo for wider use. I'd appreciate a close review from @bourque, @greglucas, and @tech3371 to make sure this lines up with what they are expecting
Added new file_validation.py file, with a shared ScienceFilepathManager class (copied from Tenzin's work on sds-manager, I need to add her and Laura as coauthors actually), which I refactored slightly for more wide adoption. Also added some useful shared methods in that file and a list of valid instruments and levels. 
I moved the project to poetry (don't leave me unattended) to match the other projects. No new dependencies there though
- imap_data_access/io.py
- updated to move some logic out of the function and use the new shared …
=> Adding universally useful file path and file name management to imap-data-access

.github/workflows/release.yml
I noticed the release workflow would run both jobs at the same time, when the pypi publish step has a dependency on the release step. 
Checked this on my fork: https://github.com/maxinelasp/imap-data-access/actions/runs/7892399492
=> Minor bugfix to release workflow

README.md, imap_data_access/__init__.py, imap_data_access/cli.py, imap_data_access/file_validation.py, imap_data_access/io.py, tests/test_file_validation.py, tests/test_io.py
This follows the new file naming convention that the SPDF would like to follow. Changing some underscores to hyphens and adding an optional repointing field.
There is now a 4-digit repointing field that is `None` if it isn't present. Do we want to add `rp` or some other clarifier before that field to indicate what it is?
=> FIX: Update the filename conventions and parsing

imap_data_access/cli.py
The repointing is an optional parameter, so if it is None we should print an empty string in the format table.
closes #26
- new file 1
=> FIX: Repointing should be an empty string when not present

imap_data_access/cli.py
If there is an error currently we print out a long stack trace. We can change this to just print the error message through a parser error rather than via the full stack trace when using this package as a CLI utility.
Testing with just query and no parameters provides this output now.
```bash
imap-data-access query
usage: imap-data-access [-h] [--version] [--data-dir DATA_DIR] [--url URL] [--debug]
[-v]
{download,query,upload} ...
imap-data-access: error: At least one query parameter must be provided
```
closes #30
=> MNT: Exit with a parser error from the CLI

.gitignore, imap_data_access/__init__.py, imap_data_access/file_validation.py, imap_data_access/io.py, tests/test_file_validation.py, tests/test_io.py
This adds the ability to download and upload SPICE files to the SDC. There is a mapping based on the SPICE file extension to which subdirectory it will go to.
Also closes #23 because we are now always inferring the directory structure from the filename, even if a full path was given to the file.
```bash
imap-data-access -v download imap_001.tf
imap-data-access -v download imap_mag_l1a_burst-magi_20240314_v001.cdf
```
I added a test_science_file and test_science_path now because we require explicit science file paths or SPICE paths for download/upload now, so this makes it easier to re-use during tests.
=> ENH: Allow SPICE file downloads/uploads

imap_data_access/cli.py
There was an annoying mismatch before, so a quick fix to align things.
Before:
```
imap-data-access query --instrument mag --data-level l1a
Found [10] matching files
---------------------------------------------------------------------------------------------------------------|
Instrument|Data Level|Descriptor|Start Date|Repointing|Version|Filename                                          |
---------------------------------------------------------------------------------------------------------------|
```
=> MNT(cli): Align hyphens/end-column separator in cli row separator

imap_data_access/__init__.py, imap_data_access/io.py, pyproject.toml, tests/conftest.py, tests/test_io.py
I messed up, and didn't fully test the previous version I guess. There was an issue when NOT using an API-key, and we want users to be able to go through either route and let the server complain not our application.
There was an error converting None-type, so we need to explicitly make it an empty dictionary rather than adding {"Header-value": None} to the request.
I have added a more explicit test for the None/expected-string case now.
I have tested this on the dev server and all uploads/downloads worked for both science and spice files.
=> Fix api key used for uploads

pyproject.toml
When a `data/` directory is present it is ambiguous which modules/packages we want to release, so explicitly set this to be only "imap_data_access".
Add pre-commit and tests to the dev optional dependencies for initial installs.
=> MNT: Update pyproject with explicit package resolution

README.md, imap_data_access/io.py, tests/test_io.py
Our APIs don't require the full path anymore, they can use just the filename and infer the directory structure. This is helpful for the upload to be able to upload a file from the current working directory.
```python
imap-data-access -v upload imap_mag_l1a_burst-magi_20240314_v007.cdf 
INFO:imap_data_access.io:Uploading file /Users/grlu5547/code/imap/imap-data-access/data/imap/mag/l1a/2024/03/imap_mag_l1a_burst-magi_20240314_v007.cdf to https://api.dev.imap-mission.com/upload/imap_mag_l1a_burst-magi_20240314_v007.cdf
HTTP Error: 409 - Conflict
Server Message: "imap/mag/l1a/2024/03/imap_mag_l1a_burst-magi_20240314_v007.cdf already exists."
```
closes #41
=> FIX: Remove restriction on upload data directory structure

imap_data_access/cli.py
We were catching the exception and printing the message to format the string nicer and not raise errors from the cli. But, when testing with another command line program we weren't getting a known error due to the zero exit code. This moves the handling of the try/except up into the parser and just directly exits with a non-zero exit code.
```bash
imap-data-access --data-dir /a/b/c upload a/b/c
imap-data-access download imap_codice_l1a_hskp_20240515_v001.cdf
```
=> FIX: Provide non-zero exit code when an action fails

imap_data_access/cli.py
Making the output table larger to accommodate longer strings and be a bit easier to read. 
Here is the Original Output: 
And Here is what I changed it to:
Let me know if you have any preferences!
Closes #57 
- cli.py
- edits made to `format_string` and `hyphens`
=> Query Table Output

api_demo.ipynb, examples/api_demo.ipynb
This PR adds a notebook that provides a demo of how to use the `data-access-api` command line tool and `data_access_api` python package. This is intended to be presented at the IMAP Science Team Meeting on August 2nd.
There is one piece of the notebook that has a hard-coded path to a directory path on my particular system. I wasn't sure how to avoid this. We will need to specify a local directory in order for file uploads to work.
We could possibly add `jupyter` as a dependency to this repo if we want users to be able to run this notebook themselves. Currently, I assume the if the user wants to do this, they will have installed `jupyter` into their environment by other means.
- `api_demo.ipynb`
- The notebook
=> API demo notebook

imap_data_access/cli.py, tests/test_cli.py
Fixing the import statement and adding a test file for the cli so the error does not slip through again.
Closes #81 
-test_cli.py
- cli.py
=> Bug Fix For CLI crash

imap_data_access/cli.py
Making changes to the `_print_query_results_table()` so the sizing of the table can be dynamic based on the `query_results` received. 
Closes #53 
- cli.py
=> Change For Dynamic Table Output

imap_data_access/io.py
When querying the database with `version` == `latest`, but no matching data exists, Python errors. This change fixes the issue.
N/A
N/A
N/A
- `io.py`
- add check to make sure at least one data point exists before looking for latest version
Tested locally with and without data
=> Error when querying "latest" version when no data exists in database

imap_data_access/io.py, tests/test_io.py
When deploying a new bucket in a non us-east-1 region, it can take time to propagate to propagate the DNS records and thus AWS will give us a 307 redirect to a region-specific endpoint. This only matters for PUT requests because those aren't supposed to be followed by default and therefore Python raises an HTTPError with a 307 code that we catch. So we can do the redirect ourselves from within there.
The attempted fix in `sds-data-manager` didn't fix the issue apparently when deploying fresh this morning. This does fix the issue from within `imap-data-access` instead.
=> MNT: Follow 307 redirects from AWS

imap_data_access/file_validation.py, tests/test_file_validation.py, tests/test_io.py
It is currently `/imap/spice/ck/...`
We are changing it to `/spice/ck/...`
and dropping the imap/ prefix to separate out spice into its own separate directory.
=> MNT/FIX: Removing imap/ prefix from SPICE files

imap_data_access/__init__.py, imap_data_access/file_validation.py, imap_data_access/io.py, tests/test_io.py
Input validation code for all input parameters. This should avoid most if not all 502 errors triggered when incorrect data is passed to the query and it crashes. 
Also introduced a test to iterate over bad input values and check that the correct valueError message is returned. 
Closes #55 
- io.cli
- tests/test_io.py
=> Input validation to handle 502 Errors

imap_data_access/__init__.py
closes #98
IDEX is now distinguishing its L2 data products as L2A and L2B.  The valid data levels should be updated to reflect this.
- "l2a" and "l2b" strings were added to the "VALID_DATALEVELS" set
=> Add l2a and l2b to valid data levels

imap_data_access/file_validation.py, tests/test_file_validation.py
closes #100
Added paths for spin and repointing data in `spice/` directory on s3.
- Added spin and repoint updates
=> Refactor file validation to handle spin and repoint file extensions

imap_data_access/file_validation.py, tests/test_file_validation.py
closes #110 
MOC's repointing data's filename is `imap_2025_230_2025_230_01.repoint.csv`. This PR fixes to match it.
- update SPICE directory mapping dict
tests/test_file_validation.py
=> SPICE: fix repoint csv filepath

.github/workflows/release.yml, imap_data_access/file_validation.py, tests/test_file_validation.py
update repoint data's folder path from `spice/repointing` to `spice/repoint` to match its filename and also to match spin folder path.
- update folder path
- .github/workflows/release.yml
- updated version to fix build fails
tests/test_file_validation.py
=> MNT: Fix PyPI build error and update repoint folder to match it's filename

imap_data_access/__init__.py, imap_data_access/file_validation.py, tests/test_file_validation.py
This PR fixes some bugs I discovered while testing the downloading of ancillary files, namely adding in a missing import, and checking for a valid `end_date` only if one is supplied.
=> Fixed some small bugs in ancillary file validation step

examples/api_demo.ipynb
This PR updates the `examples/api_demo.ipynb` notebook to showcase the latest version of `imap-data-access` and its latest capabilities; namely adding an example of querying with the `--filename` parameters, and downloading ancillary files.
For reviewers: Unfortunately it is not easy to compare changes in Jupyter notebooks on GitHub. I would suggest taking a look [here](https://github.com/bourque/imap-data-access/blob/api_demo_notebook_updates_feb_2025_STM/examples/api_demo.ipynb) to see what the end product looks like.
Closes #121
=> API demo notebook updates for Feb 2025 STM

imap_data_access/__init__.py, imap_data_access/processing_input.py, tests/test_processing_input.py
This is to simplify download dependency in general. Greg, Luisa and I discussed some approach and we thought this change may help on `imap_cli` update work. Right now in `cli.py`, we have to go through `filename_list` and then create `construct_path()` and then download each dependency files. Then we loose that information after download. With this change, we create download path list and store in the class and store in its `file_path_list` parameter. Then use that to download the file in `cli.py` and then return `InputCollection()` to all our instrument processing code.  Instrument processing code can use that information to look up their downloaded file from `file_path_list` and also allow them to have other additional informations from `InputCollection()` in processing, such as …
=> MNT: fixing file path list to have download path

imap_data_access/file_validation.py, tests/test_file_validation.py
Per the bugs found in #123 , adding tests to validation ancillary file paths to avoid them. 
Closes #123 
Turns out it was simple miss spelling error because csv is not the same as cvs.
- 
- 
- test_file_validation.py
=> Adding Ancillary File Path Test(s)

imap_data_access/__init__.py, imap_data_access/file_validation.py, tests/test_file_validation.py, tests/test_processing_input.py
Making updates to ancillary filename convention to match this [doc](https://imap-processing.readthedocs.io/en/latest/data-access/calibration-files.html) which instrument are using
- update to fix filename convention
- imap_data_access/file_validation.py 
- updates to fix filename convention
=> BUG: fixing ancillary filename convention

.github/workflows/release.yml, .github/workflows/test.yml, pyproject.toml
I ran `twine check dist/*` locally and it still failed even with the newer setuptools 🤷  Just ignore the metadata for now. There are still open issues surrounding this upstream.
Update the CI Action to build the wheel distribution as well.
Following these steps to update the CI job: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
=> MNT/REL: Update license formatting for setuptools build

imap_data_access/__init__.py, imap_data_access/cli.py
`ialirt` and `spacecraft` aren't actual instruments, but they are additional data sources for packet definitions and processing. So we need to be able to specify these on the command lines and through validation functions.
=> ENH: Add ialirt and spacecraft as valid instruments

imap_data_access/__init__.py, imap_data_access/cli.py, imap_data_access/io.py, imap_data_access/webpoda.py, pyproject.toml, tests/conftest.py, tests/test_io.py, tests/test_webpoda.py
We need to download L0 data from the POC. This brings the script I shared in Slack into our imap-data-access repository so we can use it across the project and keep all the io-related tasks in one repository. This helps to download the data to `IMAP_DATA_DIR` and generates the L0 filepath based on the ScienceFile requirements.
This is a separate URL on-premises. It requires authentication so we add a new `IMAP_WEBPODA_TOKEN` environment variable to get that externally.
Add a new cli subcommand to query webpoda specifically. Test with the following command.
```
imap-data-access webpoda --instrument swapi --start-date 20241202
```
=> ENH: Add webpoda download capability to the project

imap_data_access/processing_input.py, tests/test_processing_input.py
get_file_paths() would raise on both options being None, but we can simplify this to return all paths in that case, which can then be used in the download function to simplify that.
=> MNT: Allow for all files to be returned from input collection

imap_data_access/__init__.py, pyproject.toml
* Bump the version number to 0.16
* Import the version number from the installed metadata rather than having to manually keep these in-sync
=> REL: Updating version for v0.16

imap_data_access/file_validation.py, tests/test_file_validation.py, tests/test_io.py, tests/test_processing_input.py
Adding in file name parsing for SPICE files
None
None
None
- Added more strict regex to the SPICE files 
- Added an "extract" method that will return the spice type/version information
- Added a new mapping dictionary to convert the types in the file names into something more readable
- Added unit tests to ensure the "extract_parts" method worked
- Updated a few unit tests to use real SPICE file names
- tests/test_io.py
- Updated a unit test to use real SPICE file names
- Updated a unit test to use real SPICE file names
The tests already cover a large portion of the SPICEFilePath class, but I added tests to make sure we could extract file type/version information from all of the …
=> Spice files

imap_data_access/webpoda.py, tests/test_webpoda.py
It turns out the ENA teams do want data downloaded based on repointing, so this adds the capability described in #141.
This queries by ERT, but then groups based on repointing rather than by day. The repointing knowledge is external and requires the repointing file to be passed in.
closes #141
=> ENH: Add a method to download repointing data

imap_data_access/file_validation.py, tests/test_file_validation.py
This updates the expected filename convention for the sclk kernel to use `imap_sclk_####.tsc` I updated the type-mapping portion rather than adding a new/different regex. Updating the regex directly caused naif and other filenames to fail. Not sure if this is the most robust approach or if others want another regex for this specifically.
closes #160
=> MNT/FIX: Update SPICE sclk expected filename mapping

imap_data_access/file_validation.py, tests/test_file_validation.py
Adding MOC attitude and ephemeris metakernel to the list.
- changes to add it to the metakernels
=> Adding MOC metakernel to the list of expected kernels

imap_data_access/__init__.py
Adding zip and dat as acceptable file extensions for ancillary files. Closes #170.
N/A
N/A
N/A
- `imap_data_access/__init__.py`
- Additional file extensions
=> Add zip and dat as acceptable ancillary file extensions

imap_data_access/file_validation.py, tests/test_file_validation.py
We want one source of truth for the extension matching and not to have to update it in multiple places.
closes #172
=> FIX: Add extension handling to regex matching

imap_data_access/webpoda.py, tests/test_webpoda.py
In the title. The MOC changed the repointing column name in the last update, so we failed on the last download because of this rename.
=> FIX: Repointing column was renamed to remove "time"

pyproject.toml
Many users have run into issues with certificate verifications. Lets add certifi as a dependency to match what requests does. This can be removed if we do switch over to requests in the future because requests already has this as a dependency.
Using the same versions as requests: https://github.com/psf/requests/blob/c4c8e20289ab82edad55d2fc07b42cbf08ae1441/setup.py#L40
Both the POC and Menlo are asking for this.
=> DEP: Add certifi as a dependency

imap_data_access/webpoda.py, tests/test_webpoda.py
Remove the T and change it to a space.
Found this while trying to download the repointing data locally using the latest version in our s3 bucket.
=> FIX: Repointing file timestamps don't have T in the UTC format

pyproject.toml
There have been a few clarger changes like adding a dependency (certifi), so lets do a minor version bump.
Waiting on https://github.com/IMAP-Science-Operations-Center/imap-data-access/pull/178 before actually releasing.
=> REL: Version bump to 0.19.0

imap_data_access/io.py, imap_data_access/webpoda.py, pyproject.toml, tests/conftest.py, tests/test_io.py, tests/test_processing_input.py, tests/test_webpoda.py
External users have issues with certificate verification, so to make things easier on them we can use the requests library instead of the standard library. This also simplifies some of our handling of redirects and query parameter encoding as those come along for free with requests.
I've tested the download/upload/query/webpoda cli and all appear to be working as I'd expect still.
closes #106
requests
Note that I spent some time trying to figure out how to mock a 307 response to follow a redirect, but since requests automatically handles that for us I couldn't get something to work that wasn't just testing my mock implementation. Happy for suggestions if there are any, but otherwise our critical piece is just that we don't raise on a 307 which we did previously and we don't here in the …
=> ENH: Switch over to requests for I/O

imap_data_access/processing_input.py, tests/test_processing_input.py
Replace check for script descriptor equality with check for `descriptor in input_type.descriptor`. 
Test the new and existing behavior.
=> Allow looser dependency descriptor

imap_data_access/cli.py, imap_data_access/file_validation.py, imap_data_access/io.py, tests/test_io.py
This makes it so you can query against repointing using `--repointing repoint00001`. The actual API still takes in an integer, because the file tracking table uses ints instead of the `repointxxxxx` standard name. So this takes in `repoint00001` and transforms it before querying the HTTPS API. 
Before, the query failed because some parts were validating against `repointxxxxx` and some were validating against an integer. I think we should leave the repointing as an int in the database and in the query API, but match the standard on the outward facing wrapper here.
=> Fixing repoint keyword in query

imap_data_access/file_validation.py, tests/test_file_validation.py
updated to ignore all case sensitive and updated SFF convention to match new filename convention.
- main update
=> MNT: loosen MOC's filename convention by ignoring all case sensitive checks. Update SFF convention

imap_data_access/processing_input.py, tests/test_processing_input.py
Adding features to SPICEInput class to take in SPICE files. This will allow SPICE to be added on batch starter and imap_processing CLI.
- Added features to support SPICE files in the ProcessingInputCollection
- Good amount of tests to show how SPICE will be added and queried in batch starter and `imap_processing`'s `pre_processing()`
=> ENH: Adding SPICEInput capabilities

imap_data_access/file_validation.py, tests/test_file_validation.py
Add new filename convention to imap-data-access's file_validation.py file. Update _SPICE_TYPE_MAPPING and _SPICE_DIR_MAPPING. Then add regex in SPICEFilePath() class.
For filename: imap_dps_yyyy_doy-repoint<xxxxx>_##.ah.bc
- file_validation.py
- added dps filename convention
- test_file_validation.py
=> ENA DPS - added dps filename convention

imap_data_access/processing_input.py, tests/test_processing_input.py
I wanted to filter out ancillary fileinputs but there wasn't a method to do so. So this is a general filtering method for ProcessingInputCollection. 
It does replace get_science_inputs() but that's used elsewhere so I just wrapped the new method. 
- Add new get_processing_inputs method
- Update existing methods to use get_processing_inputs internally
=> Add a new filtering method to ProcessingInputCollection

imap_data_access/cli.py, imap_data_access/io.py, tests/test_io.py
Adding `ingestion_start_date` and `ingestion_end_date` to the `imap-data-access` API command line. 
Waiting for the `sds-data-manager ` side of the work to be merged and deployed first before I can fully test it. 
- tests/test_io.py
- imap_data_access/cli.py
- imap_data_access/io.py
=> Adding Query by Ingestion date

imap_data_access/file_validation.py, tests/test_file_validation.py
Whenever we are generating a path we should generate it from the current value of our configuration dictionary. Currently we are setting that and storing that attribute on the class at initialization. This also makes the handling of this consistent in all of the subclasses.
=> MNT: Deprecate self.data_dir

imap_data_access/__init__.py, imap_data_access/file_validation.py, imap_data_access/io.py, tests/test_file_validation.py
This follows the same naming convention as Ancillary Files, but a different set of extensions and download location.
One thing of note is that we have `imap/instrument` for science files, `imap/ancillary/instrument` for ancillary files, and `spice/` for spice files (notice the lack of `imap/`). Do we want to bring ancillary/quicklook up a level to be more akin to spice? Bring spice into the `imap/` directory structure? Or it is all OK and not a big deal.
=> ENH: Add quicklook filepath

imap_data_access/file_validation.py, imap_data_access/processing_input.py, tests/test_file_validation.py
We were having to catch each error individually which added for a lot of boilerplate code. The real root is that it is an ImapFileError and we don't really care which class was throwing it, the message gives us details there. Lets consolidate these into one common Exception on the base class and catch that in our checks for any conversion instead of special casing each individual exception. This makes the loops easier to comprehend.
I chose to leave the previous Exceptions in place in case other services were using them and just subclassed the new BaseException class, so everything is backwards compatible here too.
=> MNT: Consolidate filepath errors into the base class

imap_data_access/__init__.py, imap_data_access/file_validation.py
This brings it into alignment with our other variables to specify the conventions on the classes themselves and reference them as class vars.
This is not backwards compatible, but it doesn't look like these were used elsewhere, so I'm calling this one a cleanup of the global namespace.
=> MNT: Move FILENAME_CONVENTIONs onto classes they are associated with

imap_data_access/file_validation.py, tests/test_file_validation.py
Adding cadence file path class to be able to write cadence serialize() input to a s3 and then download in processing code.
- adding cadence class. similar to quicklook product, we are storing these cadence input into s3 path.
=> ENH: Cadence filepath

imap_data_access/processing_input.py, tests/test_processing_input.py
Update to be able to deserialize spin and repoint data
- update to be able to deserialize spin and repoint data
=> MNT: adding Spin and Repoint to the deserialize()

imap_data_access/file_validation.py, tests/test_file_validation.py
Updating the pointing attitude kernel to match the attitude history kernel name.
- remove repointNNNN from regex
- add end_year_doy group to regex
- Update test coverage for new naming convention
Closes: #223
=> 223 update imap dps kernel naming convention

imap_data_access/webpoda.py
We only passed in start_date to our query before, but this does a >= search into the future, which meant that during our I&T testing when more files are uploaded and in the future, we can accidentally match on them. We only want the specific day of this file, so add the end_date parameter as well.
Noticed this when downloading MAG packets with today's date and I was getting a v004 file because there is future 2026 files in our DB that the query matched against.
=> FIX: Add end_date to query to restrict future file searches

imap_data_access/webpoda.py, tests/test_webpoda.py
I decided to just update the SID number directly rather than allowing for this to be optional/passed through. I think we can add that capability later if it is desired, but theoretically now everyone will only want to get flight packets and not care about pre-launch anymore. We can always downgrade this tool to versions <0.35 to get pre-launch data too if desired I suppose.
closes #267
=> MNT: Update webpoda url to pull from after launch location

README.md, imap_data_access/__init__.py, tests/test_config_options.py
=> ENH: Update to use the production url by default!

imap_data_access/webpoda.py, tests/test_webpoda.py
We are getting files with NaN values in the middle and that is causing the first conversion to date of the start_time to fail now. Check for that case and skip over any repointings with an invalid start date.
=> FIX: Handle potential NaNs in the middle of the repointing files
