IMAP-Science-Operations-Center/imap-data-access

- .github/workflows/test.yml
- imap_data_access/io.py
> CI: Install optional test dependencies in actions runners

- imap_data_access/cli.py
- extra debug print hanging around
- There is no output from the upload function, so print the original file
> MNT: Cleanup cli prints

- imap_data_access/io.py
- tests/test_io.py
This wraps the urlopen request in a try/except handler that reads any content returned from the server (like helpful error messages) and raises a new `IMAPDataAccessError` with that content in the message.
> ENH: Print error messages when retrieving content

- README.md
- imap_data_access/cli.py
- change hyphen to underscores in command line arguments
- add a table and json output options
- update the README with some explicit examples
> MNT: Updates to command line arguments

- imap_data_access/__init__.py
- imap_data_access/cli.py
- pyproject.toml
> REL: Bump version to 0.2.0 and add version to command line

- imap_data_access/cli.py
This PR updates some of the help strings, and adds some of them as `descriptions` so that using the `-h` flag will (hopefully) provide all of the info a user might need.  Here is what the output looks like:
```
mabo8927: imap-data-access -h
usage: imap-data-access [-h] [--version] [--data-dir DATA_DIR] [--url URL] [--debug] [-v] {download,query,upload} ...
This command line program accesses the IMAP SDC APIs to query, download, and upload data files.
positional arguments:
{download,query,upload}
download            Download a file from the IMAP SDC to the locally configured data directory.
query               Query the IMAP SDC for files matching the query parameters. The query parameters are
optional, but at least one must be provided.
upload              Upload a file to the IMAP SDC. …
```
> More comprehensive help/descriptions

- .github/workflows/release.yml
- imap_data_access/__init__.py
- imap_data_access/file_validation.py
- imap_data_access/io.py
- tests/test_file_validation.py
Some updates to file validation
Added a new way to create a class using instrument, version, startdate, etc rather than a filename
removed data_dir argument to use config
- file_validation.py
- Moved to using config and env var
- added a new way of creating an instance: `science_file = ScienceFilePath.generate_from_inputs(...)`
Fixed tests to align with config
> File validation updates 

- imap_data_access/cli.py
- imap_data_access/file_validation.py
- imap_data_access/io.py
- tests/conftest.py
- tests/test_io.py
This PR adds some missing type hints
> Add missing type hints

- imap_data_access/__init__.py
- pyproject.toml
Updates for recent filename changes
- new file 1
> REL: v0.5.0

- imap_data_access/__init__.py
- pyproject.toml
Bump version to v0.5.1
Will release to GitHub/PyPI after this goes in. Let me know if you think I missed anything else we need to update, or if you think this should be a minor instead of a patch (I think it is only bugfix here).
> REL: v0.5.1

- imap_data_access/__init__.py
- pyproject.toml
Want to make a new release so we can add the SPICE integration into sds-data-manager. Bumping up to 0.6.0 now since there are changes.
> REL: Update to version to 0.6.0

- .all-contributorsrc
- README.md
Added the all-contributors bot to the README.md similar to imap_processing.
None
- .all-contributorsrc
- Holds formatting code, and contributors information.
None
- README.md
- Added contributors section.
None needed.
> [WIP] Bot all-contributors

- imap_data_access/cli.py
- imap_data_access/io.py
Made changes in the cli to catch if `--version latest` is passed in. Version would then need to be removed in order for a correct query to be returned. That query is then filtered based on what the greatest version number is. 
Closes #38 
- cli.py
> API Version Latest Query Return

- imap_data_access/cli.py
Only a small change to the help messages for the end and start date to explain them better. 
Closes #56
- cli.py
> API End Date Message

- imap_data_access/cli.py
Giving the option to query to see if a certain file based off of a given file path is present. Users would pass in `query --filename [File]` and the file will either be returned or no matching files will be returned. 
To avoid overwriting other passed in parameters, the filename must be the only argument passed in to the query.
Closes #59 
- cli.py
- added `--filename` to acceptable arguments
- Code to pass the given file information into the query
>  Query By Filename

- imap_data_access/__init__.py
- pyproject.toml
Updated version numbers for release `v0.8.0`
> REL: v0.8.0

- imap_data_access/__init__.py
- pyproject.toml
Updated version numbers for release `v0.9.0`
> REL: v0.9.0

- imap_data_access/__init__.py
- pyproject.toml
> REL: Bump to version v0.10

- imap_data_access/__init__.py
- pyproject.toml
Releasing a candidate release to see if this fixes bug in Infrastructure caused by this module's version `0.10.0`
- candidate release version
- candidate releaase version
> REL: v0.10.1rc1

- imap_data_access/__init__.py
- pyproject.toml
Releasing last release since something in last release version `0.10.0` introduced bug in infrastructure.
- re-release version
- re-releaase version
> Re-release new version

- imap_data_access/__init__.py
- imap_data_access/file_validation.py
- pyproject.toml
> Adding my changes to the pre-commit auto PR

- imap_data_access/__init__.py
- pyproject.toml
Updated version numbers for release v0.12.0
> REL: v0.12.0

- imap_data_access/__init__.py
- imap_data_access/file_validation.py
- imap_data_access/io.py
Using the ScienceFile class as a model I will be implementing similar code to support the upload and downloads of ancillary files with the api. 
- __init__.py
- file_validation.py
- io.py
> Support for Ancillary Files, Creating Ancillary File Class

- imap_data_access/__init__.py
- pyproject.toml
Updated version numbers for release `v0.13.0`
> REL: v0.13.0

- README.md
- imap_data_access/io.py
Update link to IMAP Data Access documentation
N/A
N/A
N/A
`README` to update link
Link works!
> Update link to IMAP Data Access documentation

- imap_data_access/__init__.py
- pyproject.toml
This PR updates the version numbers for release `v0.13.1`, which fixes bugs that were in `v0.13.0` (see #124)
> REL: v0.13.1

- imap_data_access/__init__.py
- pyproject.toml
Release requested by @lacoak21 so she can start using the dependency abstraction tools.
Changed version numbers.
> REL: 0.14.0

- imap_data_access/__init__.py
- pyproject.toml
> version bump to v0.15.0

- imap_data_access/__init__.py
- pyproject.toml
> Version update

- imap_data_access/processing_input.py
- tests/test_processing_input.py
Updated get science files to take in `source` and `descriptor` to simplify code in `imap_processing` cli code. Added `download()` method in collection class for the same reason as previous.
- code changes of updating and adding download method
> ENH: updatating get files function and add download function

- pyproject.toml
Bump the version for a new release to get the SPICE and proper MAG apids included.
> REL: Bump version to 0.17

- imap_data_access/webpoda.py
- tests/test_webpoda.py
While testing this during a time with no packets on an instrument. I noticed that we failed with a ValueError for indexing into `packet_times[-1]` when `packets_times` was empty. This catches that error and gracefully returns now instead.
I also noticed that one of the logs didn't have an f-string added for apid so added that above as well.
> FIX: Handle empty packet returns and add more logging

- pyproject.toml
Bumping the version to prepare for a new release.
> REL: Version bump to 0.18.0

- pyproject.toml
Making release for new data level.
> Prepare for release V0.18.1

- pyproject.toml
Prepare a new release of imap-data-access to help with filename handling and webpoda downloading.
> REL: Version bump to 0.18.2

- imap_data_access/cli.py
- imap_data_access/io.py
- imap_data_access/webpoda.py
- tests/test_cli.py
- tests/test_io.py
Previously, a FileNotFoundError would just display the path to the missing file as a response, but wouldn't tell you that there was an error.
Additionally, go through the code and upgrade some logs to info and add some more debug logs. This was purely subjective, so happy to change some of these if people want. The biggest thing is to add "success" INFO logs instead of just debug as people want to know when something succeeded too not just failed.
> MNT: Improve error messages and add more logging

- pyproject.toml
Patch version bump to include better logging/error messages.
> REL: Version bump to 0.20.1

- pyproject.toml
Making new release with couple new improvements.
- version bump
> MNT: Release v0.21.0

- imap_data_access/file_validation.py
- imap_data_access/processing_input.py
- tests/test_file_validation.py
- tests/test_processing_input.py
Add filtering capabilities to the ProcessingInputCollection class. 
- Add option to pass in source in get_science_inputs.
- Create function to filter processingInputCollection for only files that are valid for the given science start_date
This will be used in batch starter when filtering the ProcessingInputCollection. 
- implement is_valid_for_start_date functions
- Add filtering by date function 
- Add function to remove files from processing input
Add tests for valid dates and filtering the ProcessingInputCollection
> Add more filtering capabilities to processingInputCollection class

- pyproject.toml
Release with new ProcessingInputCollection capabilities. Also adds L2c as a valid data level. 
- version bump
> MNT: Release v0.22.0

- tests/test_io.py
Adds test for ancillary file downloads.
closes #122
> TST: Add ancillary file download tests

- pyproject.toml
> MNT: Releaseing version 0.23.0

- pyproject.toml
> MNT: Releasing version 0.24.0

- imap_data_access/__init__.py
- imap_data_access/processing_input.py
- tests/test_processing_input.py
closes #207 
Adding changes to simplify batch starter logics.
- adding new classes for easier import
- main changes related to what batch starter need.
> Redoing SPICEInput parameters to solve inconsistency in implementation

- imap_data_access/io.py
- imap_data_access/processing_input.py
- tests/test_io.py
- tests/test_processing_input.py
closes #212 
Fixing to raise with better error
- update errors
- imap_data_access/io.py
- Fixing bug with error response
- tests/test_io.py
> BUG: fixing error response and value error response

- pyproject.toml
> MNT: version bump v0.26.0

- pyproject.toml
> MNT: bump version v0.27.0

- imap_data_access/file_validation.py
- tests/test_file_validation.py
Fixing spelling mistake of s3 folder path
- fix spelling
> BUG: fixing spelling of cadence

- pyproject.toml
> MNT: version bump to v0.28.0

- pyproject.toml
Version bump to 0.29 to get latest pointing attitude kernel filename in place.
- minor version bump
> version bump pyproject.toml

- imap_data_access/file_validation.py
- tests/test_file_validation.py
- tests/test_processing_input.py
This PR adds the regex for the SPICE science frame to the file validation regex
- file_validation
- added regex for science frame
- added `test_spice_extract_science_frame_parts` test
- added assert to `test_spice_file_path`
Closes #221
> Added Science Frame Regex

- imap_data_access/io.py
- pyproject.toml
Version bump for new release with ancillary querying and CR filename convention.
> Version bump

- imap_data_access/cli.py
For the science files, if any of the queried files has a non None CR value, a column will be added to the output table, otherwise it is not present.
As an Example: 
No CR
With CR
closes #231 
- new file 1
- cli.py
> Adding CR to Query Table When Present

- imap_data_access/cli.py
Fixes the bug linked in #232. 
Closes #232 
- cli.py
> Bug: Fixing Index Error for Empty Query Responses

- imap_data_access/file_validation.py
Ultra needs to be able to upload .pgm files.
- file_validation.py
- Added .pgm extension
> Ultra l1b - add pgm extension

- imap_data_access/cli.py
- imap_data_access/io.py
Changing the description of the latest flag to say it returns the latest version of a file per start_date instead of just day
- new file 1
> Latest Flag Wording Change

- pyproject.toml
Release new version for SPICE kernel.
> MNT: version v0.34.0 release

- imap_data_access/file_validation.py
- tests/test_file_validation.py
Fixes from POC tests
fixed file extension of Small forces file.
- update extension
> BUG: Fixing SFF file extension

- imap_data_access/file_validation.py
- tests/test_file_validation.py
> BUG: fixing repoint check logic to return as bool

- pyproject.toml
> MNT: release v0.35.0

- pyproject.toml
> REL: Bump version to v0.36
